apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::479597790430:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-NypWt4jw0yON
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::479597790430:user/arun
      username: arun
kind: ConfigMap
metadata:
  creationTimestamp: "2025-12-11T01:49:27Z"
  name: aws-auth
  namespace: kube-system
  uid: 33956aae-bab6-40e4-af5b-8e3b202d922e